apiVersion: batch/v1
kind: Job
metadata:
  name: $NAME
  labels:
    batch: $BATCH_NAME
spec:
  template:
    metadata:
      labels:
        batch: $BATCH_NAME
    spec:
      containers:
        - name: job-container
          image: $IMAGE
          env:
            - name: BATCH_NAME
              value: $BATCH_NAME
            - name: JOB_ID
              value: $JOB_ID
          resources:
            requests:
              cpu: "800m"
      restartPolicy: Never
  backoffLimit: 0